### ISSUE TITLE
对接OneBot的Python模块加载器

### ISSUE THREAD

**Issue by w1ndys** [School-Robot/Plugin-Loader#4]
https://github.com/W1ndys-bot/Module-Loader

写这个加载器的原因是，了解到了 mf 师傅的插件式加载器，但我本人并不习惯这种方法，于是就写了这个模块式加载器

由于项目主要是受师傅的启发，加了师傅项目地址的友链，如果师傅愿意的话，可以互加一下🫡🫡🫡（如果不愿意直接close就行）

**Comment by f00001111** [comment]
加了
